### ISSUE TITLE
[Bug] quarto-cli-pre-release missing `/usr/lib/quarto-cli/share/preview/quarto-preview.js`

### ISSUE THREAD

**Issue by PeterWang-dev** [trap000d/aur#4]
When using `quarto preview ${QMD_PATH} --no-browser --no-watch-inputs` to render qmd file, it report `WARNING: No such file or directory (os error 2): readfile '/usr/lib/quarto-cli/share/preview/quarto-preview.js'` .

**Comment by trap000d** [comment]
Hi,

I can't reproduce it - there are no warnings, file `quarto-preview.js` is in the right place:

```
test@test:~$ quarto preview /home/test/tmp/quarto_test2 --no-browser --no-watch-inputs  --log-level info
Preparing to preview

Watching files for changes
Browse at http://localhost:7822/
^C

test@test:~$ ls -la /usr/lib/quarto-cli/share/preview/
total 444
drwxr-xr-x  3 root root   4096 Aug 18 20:22 .
drwxr-xr-x 26 root root   4096 Aug 18 20:22 ..
drwxr-xr-x  2 root root   4096 Aug 18 20:22 jats
-rw-r--r--  1 root root    544 Aug 18 20:19 quarto-preview.html
-rw-r--r--  1 root root 434247 Aug 18 20:19 quarto-preview.js

test@test:~$ pacman -Qi quarto-cli-pre-release
Name            : quarto-cli-pre-release
Version         : 1.4.322-1
```
Could you please give some more details about your environment, in particular: version of `quarto-cli-pre-release` as well as versions of dependent packages, and how did you install it (yay, makepkg, something else)?

P.S. Please be aware this github repository is for experiments only, it's not synchronized with AUR and might contain various broken or outdated stuff. For the most recent version please refer https://aur.archlinux.org/packages/quarto-cli-pre-release
